DTUFEED/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from . import views

urlpatterns = [
    url(r'',include('feed.urls')),

    url(r'^admin/', admin.site.urls),
    url("^soc/", include("social_django.urls", namespace="social")),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name="test"),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^polls/',include('polls.urls')),
    url(r'^fbfeed/',include('fbfeed.urls')),
    url(r'^discussion/',include('discussion.urls')),
    url(r'^posts/',include('posts.urls',namespace='posts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/',include(debug_toolbar.urls))
    ]+ urlpatterns

feed/urls.py
from django.conf.urls import url
from feed import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns

app_name='feed'
urlpatterns = [
    url(r'^$',views.PostListView.as_view(),name="post_list"),
    url(r'^notes/$',views.Notes.as_view(),name="notes"),
    url(r'^post/(?P<pk>\d+)$',views.PostDetailView.as_view(),name='post_detail'),
    url(r'^post/new/$',views.CreatePostView.as_view(),name ='post_new'),
    url(r'^post/(?P<pk>\d+)/publish/$',views.post_publish,name='post_publish'),
    url(r'^map/$',views.MapView.as_view(),name='map'),
    url(r'^postAPI/$',views.PostList.as_view(),name="post_API"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)

groups/urls.py
from django.conf.urls import url
from . import views

app_name = 'groups'

urlpatterns = [
    url(r'^$',views.ListGroups.as_view(),name='all'),
    url(r'^new/$',views.CreateGroup.as_view(),name='create'),
    url(r'^posts/in/(?P<slug>[-\w]+)/$',views.SingleGroup.as_view(),name='single'),
    url(r'^join/(?P<slug>[-\w]+)/$',views.JoinGroup.as_view(),name='join'),
    url(r'^leave/(?P<slug>[-\w]+)/$',views.LeaveGroup.as_view(),name='leave'),
    
]

posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns =[
    url(r'^$',views.PostList.as_view(),name='all'),
    url(r'^new/$',views.CreatePost.as_view(),name='create'),
    url(r'^by/(?P<username>[-\w]+)/',views.UserPosts.as_view(),name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
    url(r'^delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete'),
]

groups/models.py
from django.db import models
from django.utils.text import slugify
#for urls #sapce turns to - #lowercasing things for proper url etc
import misaka
#url embedding
from django.core.urlresolvers import reverse
from django.contrib.auth import get_user_model
#gives the current user that is active
User = get_user_model()

from django import template
register = template.Library()
#related_name='user_groups' ^^this made this happen used in post_list.html
#to use custom template tags

class Group(models.Model):
    name = models.CharField(max_length=255,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    description_html = models.TextField(editable=False,default='',blank=True)
    members  = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships')
    user = models.ForeignKey(User,related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group','user')

groups/views.py
from django.shortcuts import render
from django.contrib import messages
from django.db import IntegrityError
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.core.urlresolvers import reverse
from django.views import generic
from groups.models import Group,GroupMember
from django.shortcuts import get_object_or_404

from . import models

#these Class Based Views pass the necessary vairables to templates like group etc
class CreateGroup(LoginRequiredMixin,generic.CreateView):
    model = Group
    fields = ('name','description')

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))
        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except IntegrityError:
            messages.warning(self.request,'Warning Already a member !')
        else:
            messages.success(self.request,'You are now a member')

        return super().get(request,*args,**kwargs)
class LeaveGroup(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request,'Sorry you arent in this group')
        else:
            membership.delete()
            messages.success(self.request,'You have left the group!')
        return super().get(request,*args,**kwargs)

groups/templates/groups/group_base.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/groups.css'%}">
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">

    <div id="padding">

    </div>

    {% block pregroup %}

    {% endblock %}
    {% block group_content %}

    {% endblock %}
    {% block postgroup %}

    {% endblock %}
  </div>

</div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}
{% block pregroup %}

<h1>{{group.name}}</h1>
<h2>Member count : {{group.members.count}}</h2>
<div class="content">
  {% if user in group.members.all %}

    <a href="{%url 'groups:leave' slug=group.slug%}" class="btn btn-lg btn-fill btn-warning">
    <span class="glyphicon glyphicon-remove-circle"></span>Leave</a>

    {% else %}

    <a href="{%url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning">
    <span class="glyphicon glyphicon-ok-circle">Join</span></a>

  {% endif %}
</div>
{% endblock %}
{% block group_content %}
<div class="col-md-8">
  {% if group.posts.count == 0 %}
    <h2>No Posts in the group</h2>
    {% else %}
    {% for post in group.posts.all %}
    {% include "posts/_post.html" %}
    {% endfor %}
  {% endif %}
</div>
{% endblock %}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html"%}
{% load bootstrap3 %}

{% block group_content %}
<h4>Create a new Group</h4>
<form action="{% url 'groups:create' %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" class="btn btn-primary btn-large" value="Create">
</form>
{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
  <div class="col-md-4">
    <div class="content">
      {% if user.is_authenticated %}
      <h2>Welcome back </h2>
      <a href="{% url 'posts:for_user' username=user.username %}">@{{user.username}}</a>
      {% endif %}
      <h2>Groups</h2>
      <p>Welcome to groups page</p>
    </div>
    {% if user.is_authenticated %}
    <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">
    <span class="glyphicon glyphicon-plus-sign">Create new Group</span></a>
    <a href="{% url 'posts:create' %}" class="btn btn-md btn-fill btn-default">Create Post</a>
    <a href="{% url 'posts:all' %}" class="btn btn-md btn-fill btn-primary">View Posts</a>
    {% endif %}
  </div>

{% endblock %}

{% block group_content %}
  <div class="col-md-8">
    {% for group in object_list  %}
    <a href="{% url 'groups:single' slug=group.slug %}">
        <h3>{{group.name}}</h3>
        <div class="list-group-item-text container-fluid">
          {{group.description_html|safe}}
          <div class="row">
            <div class="col-md-4">
              <span class='badge'>{{group.members.count}}</span>
              member{{group.members.count|pluralize}}
            </div>
            <div class="col-md-4">
              <span class='badge'>{{group.posts.count}}</span>
              post{{group.posts.count|pluralize}}
            </div>
          </div>
        </div>
    </a>
    {% endfor %}
  </div>
{% endblock %}