DTUFEED/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from . import views

urlpatterns = [
    url(r'',include('feed.urls')),

    url(r'^admin/', admin.site.urls),
    url("^soc/", include("social_django.urls", namespace="social")),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name="test"),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^polls/',include('polls.urls')),
    url(r'^fbfeed/',include('fbfeed.urls')),
    url(r'^discussion/',include('discussion.urls')),
    url(r'^posts/',include('posts.urls',namespace='posts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/',include(debug_toolbar.urls))
    ]+ urlpatterns

accounts/urls.py
from django.conf.urls import  url
from django.contrib.auth import views as auth_views
#LOGIN AND LOGOUT VIEWS PRE DEFINED
#imported as auth_views so to clearly diffrenetiate betwen our views
from . import views


app_name='accounts'
urlpatterns = [
    url(r'login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    url(r'logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'signup/$',views.Signup.as_view(),name='signup'),
    url(r'^login_methods/',views.home, name='login_methods'),
    url(r'^user_info/$',views.UserInfo.as_view(),name='user_info'),
]

feed/urls.py
from django.conf.urls import url
from feed import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns

app_name='feed'
urlpatterns = [
    url(r'^$',views.PostListView.as_view(),name="post_list"),
    url(r'^notes/$',views.Notes.as_view(),name="notes"),
    url(r'^post/(?P<pk>\d+)$',views.PostDetailView.as_view(),name='post_detail'),
    url(r'^post/new/$',views.CreatePostView.as_view(),name ='post_new'),
    url(r'^post/(?P<pk>\d+)/publish/$',views.post_publish,name='post_publish'),
    url(r'^map/$',views.MapView.as_view(),name='map'),
    url(r'^postAPI/$',views.PostList.as_view(),name="post_API"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)

posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns =[
    url(r'^$',views.PostList.as_view(),name='all'),
    url(r'^new/$',views.CreatePost.as_view(),name='create'),
    url(r'^by/(?P<username>[-\w]+)/',views.UserPosts.as_view(),name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
    url(r'^delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete'),
]

accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.
class User(auth.models.User,auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)#username attribute comes with pre built model user

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username','email','password1','password2')#fields from django.contrib.auth
        model = get_user_model()

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'    

accounts/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView,TemplateView
from .import forms
from django.template.context import RequestContext
from django.shortcuts import render_to_response

# Create your views here.
class UserInfo(TemplateView):
    template_name = "accounts/user_info.html"

class Signup(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

def home(request):
   context = RequestContext(request,
                           {'request': request,
                            'user': request.user})
   return render_to_response('accounts/login_methods.html',
                             )
#LOGIN AND LOGOUT VIEWS PRE DEFINED by from django.contrib.auth import views as auth_views
#and directly used in urls.py

accounts/templates/accounts/accounts_base.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/accounts.css'%}">
{% endblock %}

accounts/templates/accounts/base.html
{% extends "base.html" %}
{% load staticfiles %}

accounts/templates/accounts/login.html
{% extends "accounts/accounts_base.html"%}
{% load bootstrap3 %}
{% block content %}
<div class="container">
  <h1>Log in </h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Login">
  </form>

</div>
{% endblock %}

accounts/templates/accounts/login_methods.html
{% extends "accounts/accounts_base.html"%}
{% block content %}
 <div>
 <h1>Third-party authentication </h1>

 <p>
   <ul>
   {% if user and not user.is_anonymous %}
     <li>
       <a>Hello {{ user.get_full_name|default:user.username }}!</a>
     </li>
     <li>
       <a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a>
     </li>
   {% else %}
     <li>
       <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">Login with Facebook</a>
     </li>
     <li>
       <a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">Login with Google</a>
     </li>
     <li>
      <a href="{% url 'accounts:login' %}">Login (For Societies)</a>
     </li>
     <li>
      <a href="{% url 'accounts:signup' %}">Signup (For Societies)</a>
     </li>
   {% endif %}
   </ul>
 </p>
 </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "accounts/accounts_base.html"%}
{% load bootstrap3 %}
{% block content %}
<div class="container">
  <h1>Sign Up</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Sign Up">
  </form>

</div>
{% endblock %}

accounts/templates/accounts/user_info.html
{% extends "accounts/accounts_base.html"%}
{% load bootstrap3 %}
{% block content %}
<div id="buttons">

{% if user.is_authenticated %}
<h1>Welcome {{user.username}}</h1>
<a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">
<span>Create new Group</span></a>
<a href="{% url 'posts:create' %}" class="btn btn-md btn-fill btn-default">Create Post</a>
<a href="{% url 'posts:all' %}" class="btn btn-md btn-fill btn-primary">View Posts</a>

{% endif %}
</div>

{% endblock %}