DTUFEED/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from . import views

urlpatterns = [
    url(r'',include('feed.urls')),

    url(r'^admin/', admin.site.urls),
    url("^soc/", include("social_django.urls", namespace="social")),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name="test"),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^polls/',include('polls.urls')),
    url(r'^fbfeed/',include('fbfeed.urls')),
    url(r'^discussion/',include('discussion.urls')),
    url(r'^posts/',include('posts.urls',namespace='posts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/',include(debug_toolbar.urls))
    ]+ urlpatterns

accounts/urls.py
from django.conf.urls import  url
from django.contrib.auth import views as auth_views
#LOGIN AND LOGOUT VIEWS PRE DEFINED
#imported as auth_views so to clearly diffrenetiate betwen our views
from . import views


app_name='accounts'
urlpatterns = [
    url(r'login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    url(r'logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'signup/$',views.Signup.as_view(),name='signup'),
    url(r'^login_methods/',views.home, name='login_methods'),
    url(r'^user_info/$',views.UserInfo.as_view(),name='user_info'),
]

discussion/urls.py
from django.conf.urls import url

from . import views

app_name = 'discussion'
urlpatterns = [
    url(r'^Advices/$',views.AdvicesView.as_view(),name="advices"),
]

feed/urls.py
from django.conf.urls import url
from feed import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns

app_name='feed'
urlpatterns = [
    url(r'^$',views.PostListView.as_view(),name="post_list"),
    url(r'^notes/$',views.Notes.as_view(),name="notes"),
    url(r'^post/(?P<pk>\d+)$',views.PostDetailView.as_view(),name='post_detail'),
    url(r'^post/new/$',views.CreatePostView.as_view(),name ='post_new'),
    url(r'^post/(?P<pk>\d+)/publish/$',views.post_publish,name='post_publish'),
    url(r'^map/$',views.MapView.as_view(),name='map'),
    url(r'^postAPI/$',views.PostList.as_view(),name="post_API"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

    url(r'^createChoice/$',views.CreateChoice.as_view(),name='create_choice'),
]

posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns =[
    url(r'^$',views.PostList.as_view(),name='all'),
    url(r'^new/$',views.CreatePost.as_view(),name='create'),
    url(r'^by/(?P<username>[-\w]+)/',views.UserPosts.as_view(),name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
    url(r'^delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete'),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>DTU FEED</title>
    <!-- BOOTSTRAP -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <script
  src="https://code.jquery.com/jquery-3.2.1.js"
  integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
  crossorigin="anonymous"></script>


    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">

    </script>
    <!-- Medium Style Editor     -->
    <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>

<link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
  <link rel="stylesheet" href="{% static 'css/master.css'%}">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block extra_head %}{% endblock %}
  </head>
  <body>
    <nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon">

    </span>
  </button>
      <div class="container">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto nav nav-tabs">
        <li  class="nav-items"><a class="nav-link" href="{% url 'feed:post_list' %}">DTUFEED
          <img class="top" src="{% static 'images/navbarimages/feed.png'%}" alt="x" height="35" width="35" text-align="center"/></a>
      </a></li>
        <li  class="nav-item"><a class="nav-link" href="{% url 'feed:map'%}">Maps
          <div id="cf">
            <img class="bottom" src="{% static 'images/navbarimages/map.png'%}" alt="x" height=40 width=40 />
            <img class="top" src="{% static 'images/navbarimages/map-color.png'%}" alt="x" height=40 width=40/>
        </div></a></li>
        <li  class="nav-item"><a class="nav-link" href="{% url 'polls:index' %}">Voting Poll
          <div id="cf">
            <img class="bottom" src="{% static 'images/navbarimages/poll.png'%}" alt="x" height=40 width=40 />
            <img class="top" src="{% static 'images/navbarimages/poll-color.png'%}" alt="x" height=40 width=40/>
        </div></a></li>
        <li  class="nav-item"><a class="nav-link" href="{% url 'groups:all' %}">Groups</a></li>
        <li  class="nav-item"><a class="nav-link" href="{% url 'feed:notes'%}">Notes
          <div id="cf">
            <img class="bottom" src="{% static 'images/navbarimages/notes.png'%}" alt="x" height=40 width=40 />
            <img class="top" src="{% static 'images/navbarimages/notes-color.png'%}" alt="x" height=40 width=40/>
        </div></a></li>
        <li  class="nav-item"><a class="nav-link" href="#">Teams
          <div id="cf">
            <img class="bottom" src="{% static 'images/navbarimages/teams.png'%}" alt="x" height=40 width=40 />
            <img class="top" src="{% static 'images/navbarimages/teams-color.png'%}" alt="x" height=40 width=40/>
        </div></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Discussion
          <div id="cf">
            <img class="bottom" src="{% static 'images/navbarimages/advice.png'%}" alt="x" height=40 width=40 />
            <img class="top" src="{% static 'images/navbarimages/advice-color.png'%}" alt="x" height=40 width=40/>
        </div>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'discussion:advices'%}">Senior Advices</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
        <li  class="nav-item"><a class="nav-link" href="#">Posters</a></li>
        {% if user.is_authenticated %}
        <li  class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>
        {% else %}
        <li  class="nav-item"><a class="nav-link" href="{% url 'accounts:login_methods' %}">Login</a></li>
        {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li  class="nav-item"><a class="nav-link" href="{% url 'feed:post_new' %}">ADD</a></li>
          {% if user.is_authenticated %}
          <li  class="nav-item"><a class="nav-link" href="{% url 'accounts:user_info' %}">{{user.username}}</a></li>
          {% endif %}
        </ul>
        </div><!-- /.navbar-collapse -->
      </div>

    </nav>
    <div id="extra_padding">
    </div>
    {% block content %}
    {% endblock %}
  </body>
</html>

templates/test.html
{% extends 'base.html'%}
{% block content%}
<h1>You are now logged in {{user.username}}</h1>
{% endblock %}

templates/thanks.html
{% extends 'base.html'%}
{% block content %}
<h1>thanks for visiting</h1>
{% endblock %}